### PR TITLE
First blog post, announcing postdoc role filled

### PR DESCRIPTION
**Pull request by hlapp**
This is the first blog post for the website, announcing @gaurav joining the project. @gaurav and @ncellinese, could you please review and either add a thumbs-up reaction, or comment what should be changed or added. I would like to make the post live within a day or two.

### CODE REVIEW

**Comment by ncellinese** [comment]
Looks good by me!  I have to say though that for me and my dyslexia, it was very hard to read because of the type of fonts and the numbers associated with lines.  I made it, but just want to let you know that this is not the best writing/editing environment for me.

Nico

**Comment by hlapp** [comment]
> I have to say though that for me and my dyslexia, it was very hard to read because of the type of fonts and the numbers associated with lines.

What you looked at is what is called the _diff_. I agree that's not necessarily easy to read for non-programmers, and is also kind of pointless when adding a new file in whole (because then _every_ line by definition is added, so the diff format adds no additional information). However, GitHub has some really nice and easily accessible ways of looking at either the whole file, or the changes made, in other ways more friendly to the human eye and cognition. @gaurav or I can show you next conference call.

**Comment by hlapp** [comment]
screenshot 2016-07-25 11 32 33

@ncellinese try these two buttons for different ways to look at changes (left arrow) and the file in whole at the proposed revision (right arrow).

**Comment by ncellinese** [comment]
I am actually not that stupid. I do know how to navigate GitHub but given my disabilities  I have problems working in this environment as in several others. The different view has never helped me. Also, I don’t consider myself a non-programmer given I have programmed (albeit with difficulties) all my professional life.  It’s a frustrating process for me, but I can actually do it.  I think I recall telling you that I preferred to code on napkins  rather than in the proper environment. I do understand though that learning disabilities are hard for normal people to comprehend.  Thank you anyways.

**Comment by gaurav** [comment]
This sounds great! I love how it covers both the Evolution meeting and me joining the project. I've made a few minor edits, and I think it's ready to go.

**Pull request merged**
